server:
  port: 8084
jwt:
  secret:
    key: secret
spring:
  application:
    name: spring-cloud-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:

            - RewritePath=/user-service(?<segment>/?.*), $\{segment}


        - id: searchservice
          uri: lb://searchservice
          predicates:
            - Path=/searchservice/**
          filters:
            - CustomFilter
            - RewritePath=/searchservice(?<segment>/?.*), $\{segment}

        - id: favorite-service
          uri: lb://favorite-service
          predicates:
            - Path=/favorite-service/**
          filters:
            - CustomFilter
            - RewritePath=/favorite-service(?<segment>/?.*), $\{segment}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#server:
#  port: 8088
#spring:
#  application:
#    name: spring-cloud-gateway
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#
