#server:
#  port: 8081
#
#spring:
#  application:
#   name: userService
#  dataSource:
#   url: jdbc:mysql://localhost:3306/regdetails
#   username: root
#   password: root
#   driver-class-name: com.sql.cj.jdbc.Driver
#  jpa:
#   properties:
#    hibernate:
#     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#     ddl-auto: update
#     show_sql: true
#jwt:
#  secret.key: secret
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
