server:
  port: 8081

spring:
  application:
   name: userService
  dataSource:
   url: jdbc:mysql://localhost:3306/regdetails
   username: root
   password: Bri!!iouser2021
   jpa:
     hibernate:
       ddl-auto: update
     show_sql: true


##to make application as eureka client
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
